<?php
$labels = array();
$labels['aliases'] = 'Aliakset';
$labels['autoreply'] = 'Lähetä ilmoitus';
$labels['autoreplybutton'] = 'Tallenna';
$labels['autoreplymessage'] = 'Automaattivastauksen viesti';
$labels['autoreplysubject'] = 'Automaattivastauksen aihe';
$labels['autoresponder'] = 'Automaattivastaaja';
$labels['failed'] = 'Asetusten tallennus epäonnistui!';
$labels['forward'] = 'Edelleenlähetysasetukset';
$labels['forwardingaddresses'] = 'Lähetä edelleen osoitteeseen';
$labels['keepcopy'] = 'Säilytä kopio viestistä';
$labels['mailforward'] = 'Sähköpostin edelleenlähetys';
$labels['outofoffice'] = 'Poissaoloviesti (automaattivastaaja)';
$labels['separate_alias'] = 'Erota aliasosoitteet pilkulla';
$labels['separate_forward'] = 'Erota edelleenlähetysosoitteet pilkulla';
$labels['success_changed'] = 'Asetukset tallennettu onnistuneesti';
$labels['vacation'] = 'Loma vastaaja';
// Button text
$labels['aliasesbutton'] = 'Hae aliakset';
$messages = array();
$messages['autoresponder'] = 'Automaattivastaaja';
$messages['vacation'] = 'Loma vastaaja';
?>
